package com.example.playpal;

public class Post {
    String userId, meetingDateTime, meetingLocation, postDescription;
    // PostID is generated by a method of a global control class
    String sportType;
    String proficiency;

    public Post() {

    }

    public Post(String userId, String meetingDateTime, String meetingLocation, String postDescription, String sportType, String proficiency)
    {
        this.userId = userId;
        this.meetingDateTime = meetingDateTime;
        this.meetingLocation = meetingLocation;
        this.postDescription = postDescription;
        this.sportType = sportType;
        this.proficiency = proficiency;
    }


    public String getUserId() {
        return userId;
    }

    public String getMeetingDateTime() {
        return meetingDateTime;
    }

    public String getMeetingLocation() {
        return meetingLocation;
    }

    public String getPostDescription() {
        return postDescription;
    }

    public String getSportType() {
        return sportType;
    }

    public String getProficiency() {
        return proficiency;
    }
}
